### ISSUE TITLE
How to debug uncalibrated crystal

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-lorawan#118]
Trying to get this to work on SAML21 Xplained Pro board. All works well when I set `max-sys-rx-error` to 100, but obviously that's not the right solution. Could we add some docs on trying to find out what's wrong with the crystal (preferably without an oscilloscope). Also, I'd like to see what's actually wrong and report back to Microchip.

Workaround works fine for now, so no rush.

@hasnainvirk

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1669
