### ISSUE TITLE
Support for SX126x

### ISSUE THREAD

**Issue by jacook81** [ARMmbed/mbed-os-example-lorawan#128]
Is there a plan to support the SX1262 radio?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1783

**Comment by janjongboom** [comment]
Yes, but we don't have a public timeline for it right now. You can implement a radio driver for the SX1262 as well if you need it faster. cc @hasnainvirk

**Comment by AnttiKauppila** [comment]
Public timeline would be Mbed OS 5.13. We have already started working with it and I expect it to land into https://github.com/ARMmbed/mbed-semtech-lora-rf-drivers end of this week if no major issues are found during testing
