### ISSUE TITLE
Reason for lora_radio_helper.h includes LoRaRadio.h outside the include guard?

### ISSUE THREAD

**Issue by loverdeg-ep** [ARMmbed/mbed-os-example-lorawan#138]
Is the inclusion of LoRaRadio.h supposed to be outside the include guard?

![image](https://user-images.githubusercontent.com/24318071/57727866-8b72b800-7660-11e9-8197-b598dadccc93.png)

https://github.com/ARMmbed/mbed-os-example-lorawan/blob/master/lora_radio_helper.h#L18

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1996

**Comment by AnttiKauppila** [comment]
Moved inside guard
