### ISSUE TITLE
Could not find executable for ARMC5

### ISSUE THREAD

**Issue by cipiasentini** [ARMmbed/mbed-os-example-lorawan#147]
I'm using macOS, I've just installed Mbed cli (it supposedly contains GCC inside its package, nevertheless I downloaded from https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads and used the bin folder path for GCC_ARM_PATH variable). 
I've done everything from this guide but when trying to compile I get this error:
```
Could not find executable for ARMC5.
Currently set search path: /Users/user/Documents/MBED_LIBS/GCC/bin/
[mbed] ERROR: "/Applications/MBEDCLI.app/Contents/Resources/miniconda/bin/python" returned error.
       Code: 2
       Path: "/Users/user/Desktop/Grupo/mbed-os-example-lorawan"
       Command: "/Applications/MBEDCLI.app/Contents/Resources/miniconda/bin/python -u /Users/user/Desktop/Grupo/mbed-os-example-lorawan/mbed-os/tools/make.py -t ARM -m MTS_MDOT_F411RE --source . --build ./BUILD/MTS_MDOT_F411RE/ARM"
       Tip: You could retry the last command with "-v" flag for verbose output
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2082

**Comment by AnttiKauppila** [comment]
use GCC_ARM as your target. ARMC5 is commercial tool and if you have then check that your path has been configured properly.

**Comment by cipiasentini** [comment]
> use GCC_ARM as your target. ARMC5 is commercial tool and if you have then check that your path has been configured properly.

Oh I see, now I finally got it to compile! Thanks! 

PS. You should consider adding this solution as a note on the README because I'm pretty sure that some other ARM newbie like me will face the same problem.

**Comment by AnttiKauppila** [comment]
Great!
