### ISSUE TITLE
Uplink after cnt 192 always will be reduced to 11 bytes

### ISSUE THREAD

**Issue by charattoon** [ARMmbed/mbed-os-example-lorawan#156]
Hello,

I'm using DISCO_L072CZ_LRWAN1. I just clone this program and flash to device with original code. Then, connect to TTN. It worked well until uplink cnt 194 . It's reduce from ~25-27 bytes to 11 bytes all uplink packet

![image](https://user-images.githubusercontent.com/18901735/62274649-7c82f100-b46a-11e9-8eea-2e2db164807c.png)

It a buggy or am I missing some config? and How to solve this problem?
Thanks

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2117

**Comment by charattoon** [comment]
I found it. The problem is on a gateway. I just change a new one and a problem was gone.
