### ISSUE TITLE
OTAA Failed - Check Keys with SX1262 (Nucleo L476RG)

### ISSUE THREAD

**Issue by ankush-kapile** [ARMmbed/mbed-os-example-lorawan#158]
Hi All,

I am observing issue with SX1262 radio module (connected on nucleo L476RG board). While connecting node with US915 frequency to multitech gateway (US915 Frequency compliant) in OTAA mode RX1 slot open with random frequency. Which leads to failure in connection after retrying 12 nb trials with message "OTAA Failed - Check Keys". I am using Mbed lorawan example with SX1262 RF library.
I am able to connect radio module in ABP mode successfully.
Please let me know if anything apart from normal OTAA parameters required to be configured in mbed_app.jason file.
OR is there any other setting required in application side or gateway side ?

Below is the captured log from console output -

 FREQUENCY US915

 ../lorawan/LoRaWANStack.cpp::initialize_mac_layer(117)
Initializing MAC layer
 ../lorawan/LoRaWANStack.cpp::state_controller(1089)
 Mbed LoRaWANStack initialized

 CONFIRMED message retries : 3

 Adaptive data  rate (ADR) - Enabled

 ../lorawan/LoRaWANStack.cpp::handle_connect(896)
Initiating OTAA
 ../lorawan/LoRaWANStack.cpp::state_controller(1093)
 ../lorawan/LoRaWANStack.cpp::process_joining_state(1202)
Sending Join Request ...
 ../lorawan/lorastack/mac/LoRaMac.cpp::prepare_frame(1737)
Frame preparedto send at port 0
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1169)
TX: Channel=65, TX DR=4, RX1 DR=13
 RADIO SX1262

 Connection - In Progress ...

 ../lorawan/LoRaWANStack.cpp::process_transmission(579)
Transmission completed
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx1_window(925)
RX1 slot open, Freq = 1702132066
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx2_window(958)
RX2 slot open, Freq = 923300000
 ../lorawan/LoRaWANStack.cpp::state_controller(1097)
 ../lorawan/lorastack/mac/LoRaMac.cpp::prepare_frame(1737)
Frame prepared to send at port 0
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1169)
TX: Channel=10, TX DR=0, RX1 DR=10
 RADIO SX1262

 ../lorawan/LoRaWANStack.cpp::process_transmission(579)
Transmission completed
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx1_window(925)
RX1 slot open, Freq = 904300000
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx2_window(958)
RX2 slot open, Freq = 923300000
 ../lorawan/LoRaWANStack.cpp::state_controller(1097)
 ../lorawan/lorastack/mac/LoRaMac.cpp::prepare_frame(1737)
Frame prepared to send at port 0
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1156)
DC enforced: Transmitting in 31320 ms
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1169)
TX: Channel=64, TX DR=4, RX1 DR=13
 RADIO SX1262

 ../lorawan/LoRaWANStack.cpp::process_transmission(579)
Transmission completed
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx1_window(925)
RX1 slot open, Freq = 903000000
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx2_window(958)
RX2 slot open, Freq = 923300000
 ../lorawan/LoRaWANStack.cpp::state_controller(1097)
 ../lorawan/lorastack/mac/LoRaMac.cpp::prepare_frame(1737)
Frame prepared to send at port 0
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1169)
TX: Channel=46, TX DR=0, RX1 DR=10
 RADIO SX1262

 ../lorawan/LoRaWANStack.cpp::process_transmission(579)
Transmission completed
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx1_window(925)
RX1 slot open, Freq = 911500000
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx2_window(958)
RX2 slot open, Freq = 923300000
 ../lorawan/LoRaWANStack.cpp::state_controller(1097)
 ../lorawan/lorastack/mac/LoRaMac.cpp::prepare_frame(1737)
Frame prepared to send at port 0
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1156)
DC enforced: Transmitting in D1303 ms
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1169)
TX: Channel=68, TX DR=4, RX1 DR=13
 RADIO SX1262

 ../lorawan/LoRaWANStack.cpp::process_transmission(579)
Transmission completed
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx1_window(925)
RX1 slot open, Freq = 2717766526
 ../lorawan/lorastack/mac/LoRaMac.cpp::open_rx2_window(958)
RX2 slot open, Freq = 923300000
 ../lorawan/LoRaWANStack.cpp::state_controller(1097)
 ../lorawan/lorastack/mac/LoRaMac.cpp::prepare_frame(1737)
Frame prepared to send at port 0
 ../lorawan/lorastack/mac/LoRaMac.cpp::schedule_tx(1169)
TX: Channel=13, TX DR=0, RX1 DR=10

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2129

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”
