### ISSUE TITLE
Example broken for mbed-os master and 5.13.x

### ISSUE THREAD

**Issue by farrenv** [ARMmbed/mbed-os-example-lorawan#163]
Target: EP_AGORA
The example works through mbed-os 5.12.4.  It breaks on master and all releases 5.13.x

On master I see:
![image](https://user-images.githubusercontent.com/37904409/64650148-7dedf480-d3ec-11e9-9ca7-62ffa5948f3d.png)
5.13.4-5.13.2 Do not work at all
5.13.1 produces a hard fault
![image](https://user-images.githubusercontent.com/37904409/64650187-9b22c300-d3ec-11e9-9c69-a347951f4c5d.png)
Call stack reveals LoRa thread call to be the culprit:
![image](https://user-images.githubusercontent.com/37904409/64650233-b097ed00-d3ec-11e9-907b-a88eed6c0355.png)

![image](https://user-images.githubusercontent.com/37904409/64650242-b7266480-d3ec-11e9-982f-eb116078e376.png)

5.13.0 locks up in the same place as master:
![image](https://user-images.githubusercontent.com/37904409/64650269-c7d6da80-d3ec-11e9-9294-1cbd662ed59b.png)
Call stack reveals it is hanging out in sleep manager:
![image](https://user-images.githubusercontent.com/37904409/64650300-d7562380-d3ec-11e9-8cbf-3cc17a38ec68.png)

**Comment by trowbridgec** [comment]
@ARMmbed/team-embeddedplanet @maclobdell

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-2173

**Comment by trowbridgec** [comment]
@bentcooke @AnttiKauppila

**Comment by 0xc0170** [comment]
Can you bisect, to find out what did break it? It would be good start.

**Comment by AnttiKauppila** [comment]
It clearly runs out of memory, so something has been added into Mbed OS platform itself, because LoRaWAN stack is unmodified between those versions

**Comment by AnttiKauppila** [comment]
“At this time, due to our prioritisation of work on customer projects, we are unable to devote the time to fix this issue. As an open source project, we welcome fixes to Mbed OS, so if would like to contribute a fix yourself then we would very much welcome that, please see our contribution guidelines here - https://os.mbed.com/docs/mbed-os/v5.14/contributing/workflow.html#contributions”

**Comment by loverdeg-ep** [comment]
@AnttiKauppila @maclobdell @ranshe

This is an open source project. Internal to ARM there may be no resources to look at this, but that does not mean it is not still an active issue.

I understand why LoRaWAN is not currently a priority for ARM, but we still have paying customers using it and one of our top priorities is working towards enabling those customers to manage their devices via LWM2M; if you catch my drift.

**Comment by 0xc0170** [comment]
@loverdeg-ep Thanks for the feedback. What would you suggest? 

We shall not keep issues reported opened forever. However this issue is new so would expect to have it fixed within a month or become stale (might be closed later due to inactivity as "won't fix").

**Comment by trowbridgec** [comment]
@maclobdell This is the issue I was trying to point you to. It's still a problem, so I'd argue it should be re-opened so ARM or someone else can address it.

**Comment by farrenv** [comment]
@trowbridgec discovered a #define that limits any nordic target from using more than one Interruptin initialization with SDK 15.0 #11622
