### ISSUE TITLE
DISCO-LRWAN1 Board-->Can't send data beyond 64 bytes in uplink packet

### ISSUE THREAD

**Issue by sarwadenj** [ARMmbed/mbed-os-example-lorawan#174]
Hi, 
I'm using DISCO-LRWAN1 board with sensors.

For my application, i wanted to send around 100 bytes. So i change buffer size to 100 uint8_t tx_buffer[100]; If i print length of tx_buffer it shows 98. but it sends only first 64 bytes for transmission. Shows 64 bytes scheduled for transmission.

packet_len = sprintf((char *) tx_buffer, "{\"parkingid\":56,\"status\":%d,\"timestamp\":3,\"locationid\":\"Mall_D_MART\",\"X\":%hd,\"Y\":%hd,\"Z\":%hd}",status,magnetic_field[0], magnetic_field[1], magnetic_field[2]);
     printf("%s\n", tx_buffer);

What changes i need to do if i wanted to send more bytes?

Thanks

**Comment by AnttiKauppila** [comment]
@sarwadenj You should study the LoRaWAN regional parameters to see that with lowest datarates maximum payload size is usually 51 bytes, but it might be as low as 11 bytes (US902-928). 
These kind of questions should be posted to forum https://forums.mbed.com/
