### ISSUE TITLE
Does not compile in online compiler

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-lorawan#41]
ARMCC does not like `lorawan/bla.h` style.

**Comment by janjongboom** [comment]
See for fixes https://github.com/ARMmbed/sxsw2018/commits/master

@hasnainvirk

**Comment by 0xc0170** [comment]
Anyone to look at this?

**Comment by AnttiKauppila** [comment]
We will take care of this

**Comment by kivaisan** [comment]
@janjongboom I checked your fixes, but you only had changed some of those. Do you have any guidance which qualified paths should be listed and which not. Or should we remove all qualified paths and just include the header file?

**Comment by 0xc0170** [comment]
> @janjongboom I checked your fixes, but you only had changed some of those. Do you have any guidance which qualified paths should be listed and which not. Or should we remove all qualified paths and just include the header file?

Those paths are used in the codebase, if you review drivers/platforms. What errors are you seeing and which files? is it just lorawan files?

**Comment by janjongboom** [comment]
@0xc0170 Yes, it complains that it cannot find the header. If you remove the qualified path thing it does compile.

**Comment by janjongboom** [comment]
So right now it works. Don't know if this was fixed through the release of new ARMCC, or something else, but it works.
