### ISSUE TITLE
Add credentials to base station missing

### ISSUE THREAD

**Issue by peksaa01** [ARMmbed/mbed-os-example-lorawan#42]
Add network credentials needs information that credential must be added to base station.

**Comment by kivaisan** [comment]
Basically these credentials comes from network provider. So cannot be any generic instructions how to add credentials to lora server. 
Maybe we should add a sentence something like "Credentials are provided by LoRa network provider" to chapter Add network credentials.

**Comment by peksaa01** [comment]
Good sentence. It will give missing information for the user.

**Comment by adbridge** [comment]
@kivaisan Is this now fixed? Can we close this then ?

**Comment by kivaisan** [comment]
Yes, this is fixed.
