### ISSUE TITLE
make_armc5 exporter fails for online compiler

### ISSUE THREAD

**Issue by bentcooke** [ARMmbed/mbed-os-example-lorawan#51]
Using the NUCLEO_F411RE, export->make_armc5 fails with the following message.

![image](https://user-images.githubusercontent.com/30628036/37616838-25fbbeb8-2b7f-11e8-8ed9-fb18ffcd4fc5.png)

**Comment by janjongboom** [comment]
Tracking here https://github.com/ARMmbed/mbed-os/issues/6395.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-773

**Comment by kivaisan** [comment]
Closing this issue as tracked with other issue.
