### ISSUE TITLE
make_iar exporter fails for online compiler

### ISSUE THREAD

**Issue by bentcooke** [ARMmbed/mbed-os-example-lorawan#52]
Using NUCLEO_F411RE, the make_iar exporter fails with the following:
![image](https://user-images.githubusercontent.com/30628036/37616950-84d0a0fc-2b7f-11e8-8ce5-fe1251f441ce.png)

**Comment by janjongboom** [comment]
Tracking here https://github.com/ARMmbed/mbed-os/issues/6395.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-772

**Comment by kivaisan** [comment]
Closing this issue as tracked with other issue.
