### ISSUE TITLE
make_gcc_arm exporter fails for online compiler

### ISSUE THREAD

**Issue by bentcooke** [ARMmbed/mbed-os-example-lorawan#53]
Using NUCLEO_F411RE, the make_gcc_arm exporter fails with the following:
![image](https://user-images.githubusercontent.com/30628036/37618486-6ea21414-2b84-11e8-889c-7658b61a39d9.png)

**Comment by janjongboom** [comment]
Tracking here https://github.com/ARMmbed/mbed-os/issues/6395.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-771

**Comment by kivaisan** [comment]
Closing this issue as tracked with other issue.
