### ISSUE TITLE
lorawan-enabled setting

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-lorawan#62]
Why is there a `lorawan-enabled` setting that is now disabled by default?? On a board with Arduino pinout it should almost always work with a shield I'd say. Now the app just compiles but the application does nothing, also no warning on serial or in compilation step.

**Comment by janjongboom** [comment]
Also, no notion of this in the README.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-840

**Comment by kivaisan** [comment]
@janjongboom Please verify the fix.
