### ISSUE TITLE
Remove #ifdef DEVICE_SPI macro

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-lorawan#63]
What if my device has a LoRa radio that has no SPI (e.g. the simulator which uses a fake LoRa radio driver)? Now it won't compile. If you want this check it should go in the lora-radio-driver repo.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-839

**Comment by kivaisan** [comment]
@janjongboom Please verify the fix.
