### ISSUE TITLE
Timed uplink stops working after 72 minutes

### ISSUE THREAD

**Issue by simonnilsson** [ARMmbed/mbed-os-example-lorawan#65]
I'm using the EventQueue class to schedule regular uplinks.

```
ev_queue.call_every(60000, send);
```

When setting a timed uplink to send every 1 minute the frame-count will reach 71 and and stop sending data. I suspect this has something to do with a **32-bit integer** somewhere used to store the microsecond time which would mean it would reach about **71.58 minutes** before overflowing.

Is this a known problem or am I doing something wrong?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-844

**Comment by kivaisan** [comment]
@simonnilsson What mbed-os version and HW are you using? I just tested with our example lora app and the latest mbed-os (I'm using K64F HW with SX1276 shield) with 10000msec sending interval and so far I haven't seen any problems. My test has already been running now for 80 minutes.

**Comment by simonnilsson** [comment]
@kivaisan Hi, I'm using a custom board with an STM32L071 mcu and SX1276 radio.  Using mbed-os master from 7 days ago (c8d72c524dd7ac1b537bd5fe230572cb703f0532).

I have slightly modified the example code for my use case but I will make another test with code that resemble the original code as close a possible and let you know the result.

**Comment by simonnilsson** [comment]
It might also be relevant that I'm using **MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER**  set to **1**

**Comment by simonnilsson** [comment]
With **MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER** set to **0** it seems to work. Tested up to 90 minutes.

**Comment by kivaisan** [comment]
Could you please retest with the latest mbed-os because after https://github.com/ARMmbed/mbed-os/commit/c8d72c524dd7ac1b537bd5fe230572cb703f0532 MBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER  no longer has any effect when RTOS is used.

**Comment by simonnilsson** [comment]
I do have that commit already, it's the same as the SHA I wrote above. But I do not include RTOS, it should not be needed for this example correct?

**Comment by kivaisan** [comment]
Yes, example should work also with non-rtos. We'll check the problem with non-rtos.

**Comment by kivaisan** [comment]
I was not able to reproduce the problem yet with K64F (uplink were still working after 2 hours). I had following .mbedignore in use:

```
mbed-os/rtos/*
mbed-os/features/cellular/
mbed-os/features/FEATURE_CLIENT/*
mbed-os/features/FEATURE_COMMON_PAL/*
mbed-os/features/FEATURE_UVISOR/*
mbed-os/features/FEATURE_LWIP/*
mbed-os/features/frameworks/*
mbed-os/features/net/*
mbed-os/features/netsocket/*
mbed-os/features/nvstore/*
mbed-os/features/storage/*
#mbed-os/events/*
```

**Comment by kivaisan** [comment]
Actually yes. Low power timers might not work properly on all platforms.

**Comment by simonnilsson** [comment]
Okay, how do you recommend i proceed? Should I create another issue on the main mbed-os repository instead?

**Comment by simonnilsson** [comment]
Yes I will try that tomorrow. 

It is a custom board and I made a new target for it. I based my target on the stm32l072 and just changed the memory sizes, pin-names and peripherals to match the new mcu. So they should be using the same timer logic. 

I will get back to you when I tried a simple call_every that just toggles a led.

**Comment by simonnilsson** [comment]
Tried it with the simplest code possible: [main.cpp](https://gist.github.com/simonnilsson/e6432eaf0af8e5c2bca6e10f03d630ec)

Worked fine without Low Power Timer but stopped working after 71~ minutes with Low Power Timer.

**Comment by kivaisan** [comment]
Ok, the problem is not in the lora stack then. Could you please file a new issue to mbed-os with all these information (STM32L071 and non-RTOS etc.) and how to reproduce so there HAL team can take a look on it? And this lora issue can be closed.

**Comment by simonnilsson** [comment]
Okay, will do. Thanks for your assistance!
