### ISSUE TITLE
Project fails to compile when "lora.phy": 2 in mbed_app.json

### ISSUE THREAD

**Issue by woollettg** [ARMmbed/mbed-os-example-lorawan#67]
When I change the regional setting from 0 (EU) to 2 for AU915 the build fails with these messages-
Error: Declaration does not declare anything in "extras/mbed-os.lib/features/lorawan/LoRaWANStack.h", Line: 446, Col: 6
Error: This declaration has no storage class or type specifier in "extras/mbed-os.lib/features/lorawan/LoRaWANStack.h", Line: 446, Col: 21
All other choices 0 to 8 build.
Also how do you specify a frequency subband?  I want to use sub band 2 channels 7 thru 15.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-948

**Comment by kivaisan** [comment]
Fix-PRs:
mbed-os 5.8.x: https://github.com/ARMmbed/mbed-os/pull/6829
mbed-os master: https://github.com/ARMmbed/mbed-os/pull/6839

**Comment by AnttiKauppila** [comment]
This has been fixed in 5.8.5 release of mbed OS. Closing this
