### ISSUE TITLE
Stack thinks it's stuck in duty cycle violation

### ISSUE THREAD

**Issue by janjongboom** [ARMmbed/mbed-os-example-lorawan#76]
See https://gist.github.com/janjongboom/f5519a43353f5d7f88ff58101b361597 for the example code.

1. Disable duty cycle.
2. Set channel plan to EU868.
3. Call `send_message` in the CONNECTED handler (not by dispatching to evqueue).
4. First message is sent.
5. Every subsequent message gets a duty cycle error.

@hasnainvirk

**Comment by janjongboom** [comment]
If I change it to `ev_queue.call_in(1000, &send_message);` then it's fine.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1029

**Comment by kivaisan** [comment]
@janjongboom Just tested your app (modified my own TTN keys and changed payload from CayenneLPP to just plain uint8_t buffer) and I don't see LORAWAN_STATUS_WOULD_BLOCK error.

But I see "a problem" with ABP when using payload > 38. At least in my case lorawan seems to select DR_2 as a datarate so we hit it's max payload length (51) limit (MAC headers add 13 bytes to user payload).

**Comment by kivaisan** [comment]
And I tested with the latest mbed-os master. (See my earlier updated comment about datarate).
Also tried with both, duty cycle enabled and disabled.

**Comment by janjongboom** [comment]
@kivaisan It's only sending 6 bytes or so; the 50 bytes is just the max buffer. It's not sending all of them.

**Comment by kivaisan** [comment]
@janjongboom Could you please let us know which mbed-os version you are using to reproduce WOULD_BLOCK error?

**Comment by janjongboom** [comment]
Pretty sure this was 367dbdf5145f4d6aa3e483c147fe7bda1ce23a36 w/ SX1276 on NUCLEO-F446RE.

**Comment by kivaisan** [comment]
Tried to reproduce with 367dbdf51 in K64F/SX1276 and I still can't reproduce this problem.

**Comment by janjongboom** [comment]
OK, let's close it and if I manage to run into it again I'll reopen.
