### ISSUE TITLE
LTEK_FF1705 or FF1705_L151CC should be used

### ISSUE THREAD

**Issue by peksaa01** [ARMmbed/mbed-os-example-lorawan#77]
When compiled with MCU = LTEK_FF1705 as in mbed_app.json compiler said that it is not supported MCU. FF1705_L151CC is not found from mbed_app.json (is in -m list). 
Which one should be used?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1046

**Comment by kivaisan** [comment]
@janjongboom I think this is one of your boards. Could you please check if the FF1705_L151CC target works ok, or was this LTEK_FF1705 some special one?

**Comment by theotherjimmy** [comment]
@peksaa01 `mbed_app.json` may contain identifiers that are not targets, so long as they are part of the inheritance hierarchy of a target in question. You're correct in pointing out that the LTEK_FF1705 is not an mcu. Interestingly, it's also not in any inheritance hierarchy. I can't advise you on this, except to say pick a different board. Sorry.

**Comment by janjongboom** [comment]
I think it's just something we looked over. FF1705_L151CC target should work fine. Maybe we renamed the target at some point?

**Comment by theotherjimmy** [comment]
@janjongboom Probably not, It came in under that name: https://github.com/ARMmbed/mbed-os/pull/4973

**Comment by kivaisan** [comment]
@janjongboom We don't have the board here so I need your help to verify that FF1705_L151CC works properly.

**Comment by janjongboom** [comment]
Yes should work fine. I've been using the new stack with FF1705 target.

**Comment by hasnainvirk** [comment]
@peksaa01 There is no reason why it shouldn't work. Just use the target as FF1705. I actually played with this board when Jan was in Oulu.

**Comment by hasnainvirk** [comment]
I would recommend for 5.10 release we should do something suggested in https://github.com/ARMmbed/mbed-os/issues/6131

**Comment by kivaisan** [comment]
Closing this as fixed.
