### ISSUE TITLE
Is it possible to change tx power ?

### ISSUE THREAD

**Issue by pmancele** [ARMmbed/mbed-os-example-lorawan#87]
Hello,
It is more a question than an issue but i would like to know if it is possible to change the TX Power through the Mbed LoRa API ?
I checked the API and didn't found something that allow me to do this from the application code.

By the way, what is the default TX Power ? +27 dbm ?

Thank you,
Pierre-Marie

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCELL-1155

**Comment by hasnainvirk** [comment]
@pmancele There is no API to change the TX power as the TX power will be changed in response to a Mac command sent by the network server. This can happen either in LinkADRRequest mac command or TxParamSetupReq mac command. For network optimization, it is vital.

**Comment by pmancele** [comment]
Ok thank you for the explanations !
